### PR TITLE
Update docsearch configuration

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This change updates Docsearch configuration to use the new v3 index. Note that this requires the new changes in the theme as proposed here: https://github.com/PrestaShop/ps-docs-theme/pull/10
| Fixed ticket? | Fixes https://github.com/PrestaShop/docs/issues/1274

## How to do this

1. Merge the other PR: https://github.com/PrestaShop/ps-docs-theme/pull/10
2. Merge this PR
3. Pull the updated theme into this project, commit and push.
4. The project is published in production.

### CODE REVIEW

**Comment by matks** [comment]
https://github.com/PrestaShop/ps-docs-theme/pull/10 merged

I will test the result before merging this PR

**Review by jolelievre — APPROVED** [review]

**Comment by matks** [comment]
I'm blocked by https://github.com/PrestaShop/docs/issues/1276 but should be fixed soon

**Comment by matks** [comment]
PR works as expected

**Comment by matks** [comment]
Thank you @eternoendless

**Pull request merged**
