### PR TITLE
Fetch 0 depth for submodule to allow git pull --recurse-submodules to success

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fetch 0 depth for submodule to allow git pull --recurse-submodules to success
| Fixed ticket? | https://github.com/PrestaShop/devdocs-site/issues/4

Workflow works: https://github.com/PrestaShop/devdocs-site/runs/3290986124?check_suite_focus=true

### CODE REVIEW

**Comment by matks** [comment]
Thanks to https://dev.to/__attsun__/unable-to-find-current-origin-master-revision-in-submodule-path-error-at-github-action-actions-checkout-v2-oho

**Comment by eternoendless** [comment]
Any idea why the `fetch-depth: 0` is necessary or what it does?

**Comment by matks** [comment]
@eternoendless the GitHub Action `checkout` https://github.com/actions/checkout by default only fetches 1 commit, and it seems it means 1 branch.

As we now use `8.x` branch of docs repository, this branch is not fetched which is why git cannot find it
```
fatal: Needed a single revision
Unable to find current origin/8.x revision in submodule path 'src/content/8'
```

Fetch depth 0 will fetch all branches of the repositories according to https://github.com/actions/checkout so `8.x` is fetched too, allowing the git submodule pull to find it.

**Comment by eternoendless** [comment]
Got it 👍

**Comment by eternoendless** [comment]
Thanks @matks

**Pull request merged**
