### PR TITLE
Update hostname and fix dependencies

### PR DESCRIPTION
**Pull request by MeKeyCool**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Update Prestashop project hostname and dependencies.
| Fixed ticket? | Na.

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Looks good to me, @thomasnares can you check it works as expected?

if we merge this will go live in production 😄

**Comment by kpodemski** [comment]
I'm not sure if changes from the submodules should be part of this PR.

**Comment by thomasnares** [comment]
> I'm not sure if changes from the submodules should be part of this PR.

I'm not enough comfortable with PR with submodules, will this open/merge 2 PR on each branch on docs repo ?

**Review by matks — COMMENTED** [review]
> > I'm not sure if changes from the submodules should be part of this PR.
> 
> I'm not enough comfortable with PR with submodules, will this open/merge 2 PR on each branch on docs repo ?

No, submodules are simply a 'reference' to another git repo. They are automatically updated regularly by GitHub Actions on this repository.

@MeKeyCool unless it fixes a bug that we missed, I agree with @kpodemski : I think submodules update are not needed in this PR

**Comment by MeKeyCool** [comment]
I didn't see that submodules are auto updated by Jarvis : https://github.com/PrestaShop/devdocs-site/commit/c33e90fb72031fb7d04cbfd8ab80f69dabed8a6b

Thanks for review :+1:

**Review by thomasnares — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @MeKeyCool

**Pull request merged**
